# Generated by Django 4.2.5 on 2023-09-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupação', models.CharField(choices=[('Professor', 'Professor'), ('Estudante', 'Estudante'), ('Diretor', 'Diretor')], max_length=50)),
            ],
        ),
    ]
