# Generated by Django 4.2.5 on 2023-09-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ocupação'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('biologia', models.BooleanField(default=False)),
                ('computacao', models.BooleanField(default=False)),
                ('agropecuaria', models.BooleanField(default=False)),
                ('outros', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faltas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manter_avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_avaliacao', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Trabalho'), ('projeto', 'Projeto'), ('lista_exercicio', 'Lista de Exercício')], max_length=50)),
                ('valor', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Manter_cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Manter_cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('duracao_meses', models.IntegerField()),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Manter_disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Manter_ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manter_cursos')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('professor', models.BooleanField(default=False)),
                ('estudante', models.BooleanField(default=False)),
                ('diretor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primeiro_periodo', models.BooleanField(default=False)),
                ('Segundo_periodo', models.BooleanField(default=False)),
                ('Terceiro_Periodo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professores', models.BooleanField(default=False)),
                ('estudantes', models.BooleanField(default=False)),
                ('coordenacao', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=50)),
                ('pai', models.CharField(max_length=50)),
                ('mae', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('data_nasc', models.DateField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faltas', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matutino', models.BooleanField(default=False)),
                ('vespertino', models.BooleanField(default=False)),
                ('noturno', models.BooleanField(default=False)),
                ('integral', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Ocupação',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Nome_Pessoa',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='turmas',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nome_pessoa'),
        ),
        migrations.AddField(
            model_name='turmas',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno'),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='pessoas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoas'),
        ),
        migrations.AddField(
            model_name='manter_ocorrencias',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nome_pessoa'),
        ),
        migrations.AddField(
            model_name='manter_disciplinas',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodos'),
        ),
        migrations.AddField(
            model_name='manter_avaliacao',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodos'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='cursos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manter_cursos'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='cursos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manter_cursos'),
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
    ]
